Maximize pandas version to <2.0 as append is removed (#343)
AttributeError: 'DataFrame' object has no attribute 'append' is thrown.
Pandas 2.0 has removed 'append' as of April 2023. Short term solution is
to require pandas version to be below 2.0.

---------

Co-authored-by: miriam-groeneveld <miriam.groeneveld.diag@gmail.com>